/**
 * @file Share.h
 * @author Aman Deep Singh
 * @brief 
 * @version 0.1
 * @date 2023-06-10
 * 
 * @copyright Copyright (c) 2023
 * 
 */

#ifndef __SHARE_H__
#define __SHARE_H__

#include <iostream>
#include <vector>

using namespace std;

/**
 * @brief Represents a single share generated by Shamir's Secret Sharing algorithm.
 * 
 */
class Share {
    public :
    int x; // X coordinate
    int y; // Y coordinate
    vector<int> commitments; // Commitments to the coefficients of the polynomial

    /**
     * @brief Construct a new Share object
     * 
     */
    Share();

    
    /**
     * @brief Construct a new Share object
     * 
     * @param x 
     * @param y 
     * @param commitments 
     */
    Share(int x, int y, const vector<int> &commitments);


    /**
     * @brief Verifies the integrity and authenticity of the share.
     * 
     * @return true 
     * @return false 
     */
    bool verifyShare(int p, int g);
    
};

#endif

